
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fec892027b50c78a26a20b2f8faa0a3b1bbbe010",
 "version": "0.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
