
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-03T17:47:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c47b25d25534dca778cfe1eb7bb5dbe8b7832aa",
 "version": "1.21.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
