
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-16T10:08:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "79ca2047633a299a6331cc4c607638c1555f1f47",
 "version": "0.12.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
