
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.35.0+6.gaa35fb1'
version_full = 'aa35fb1123fac741ab4373020df0a64f7732b0fc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

