
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-25T09:04:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "120aa79ec8b3929dd02d4a838fe795df0f77af62",
 "version": "1.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
