
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "95c56a563e435117778623a91111a5ba4312b25b",
 "version": "0.15.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
