
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "19e70525510ff10e5dc38a8026a104ff55240424",
 "version": "1.6.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
