
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6e1e86bd13e53af4f8ee2d33a7f1f62450d25064",
 "version": "2.23.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
